// Package genfile lets any go-fp-lint analyzer skip files carrying the
// canonical Go "generated code" marker (go.dev/s/generatedcode), matching
// golangci-lint's own convention. Anchor: tnt task #96698 -- 7 findings
// against templ-compiler output (internal/platformapi/views/*_templ.go),
// regenerated on every `templ generate` run and outside the author's
// hand-editing control.
package genfile

import (
	"go/ast"
	"regexp"

	"golang.org/x/tools/go/analysis"
)

// generatedPattern is the canonical marker regex per go.dev/s/generatedcode
// ("Code generated by <tool>. DO NOT EDIT." on its own comment line),
// the same pattern golangci-lint recognizes.
var generatedPattern = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// IsGenerated reports whether file carries the canonical generated-code
// marker comment.
func IsGenerated(file *ast.File) bool {
	for _, group := range file.Comments {
		for _, c := range group.List {
			if generatedPattern.MatchString(c.Text) {
				return true
			}
		}
	}
	return false
}

// SkipGenerated returns a copy of analyzer whose diagnostics are filtered
// to exclude any position falling inside a file that IsGenerated flags.
// The filter operates at pass.Report, not by pruning pass.Files before
// calling analyzer's own Run -- some analyzers (e.g. impurereach) derive
// diagnostics from a whole-package SSA/type-info result computed by a
// Requires dependency rather than iterating pass.Files directly, and
// pruning Files up front would not reach those diagnostics. Filtering at
// Report instead works uniformly regardless of how an analyzer derives
// its findings, since every diagnostic still carries a pass.Fset-
// resolvable position.
func SkipGenerated(analyzer *analysis.Analyzer) *analysis.Analyzer {
	wrapped := *analyzer
	origRun := analyzer.Run
	wrapped.Run = func(pass *analysis.Pass) (interface{}, error) {
		generated := generatedFilenames(pass)
		origReport := pass.Report
		newPass := *pass
		newPass.Report = func(d analysis.Diagnostic) {
			if generated[pass.Fset.Position(d.Pos).Filename] {
				return
			}
			origReport(d)
		}
		return origRun(&newPass)
	}
	return &wrapped
}

// generatedFilenames returns the set of filenames, among pass.Files, that
// IsGenerated flags.
func generatedFilenames(pass *analysis.Pass) map[string]bool {
	generated := make(map[string]bool, len(pass.Files))
	for _, f := range pass.Files {
		if IsGenerated(f) {
			generated[pass.Fset.Position(f.Pos()).Filename] = true
		}
	}
	return generated
}
